name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest

    steps:
    # Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4

    # Setup Python
      - name: Install runtime
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

    # Install Dependencies
      - name: Install Dependencies
        run: pip install -r requirements.txt

    # Run test
      - name: Run Tests
        run: pytest

  lint:
    name: Run Linting and Formatting
    runs-on: ubuntu-latest

    steps:

    # Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4

    # Setup Python
      - name: Install runtime
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

    # Install Dependencies
      - name: Install Dependencies
        run: pip install -r requirements.txt

    # Run Ruff
      - name: Run Lint
        run: |
          ruff check .
          ruff format --check .


  build:
    name: Build the application
    runs-on: ubuntu-latest

    needs:
      - test
      - lint     

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Install runtime
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build
        run: echo "Happy Building CI/CD"