name: CI

on:
  push:
    branches: ["main"]

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install runtime
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: pip install -r requirments

      - name: Run Tests
        run: pytest