name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest

    steps:
    # Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4

    # Setup Python
      - name: Install runtime
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

    # Install Dependencies
      - name: Install Dependencies
        run: pip install -r requirements.txt

    # Run test
      - name: Run Tests
        run: pytest

  lint:
    name: Run Linting and Formatting
    runs-on: ubuntu-latest

    steps:

    # Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4

    # Setup Python
      - name: Install runtime
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

    # Install Dependencies
      - name: Install Dependencies
        run: pip install -r requirements.txt

        

    # Run Ruff
      - name: Run Lint
        run: |
          ruff check .
          ruff format --check .


  build:
    name: Build the application
    runs-on: ubuntu-latest

    needs:
      - test
      - lint     

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Install runtime
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install Build Tool
        run: pip install build

      - name: Build
        run: python -m build

      - name: Upload as Artifact
        uses: actions/upload-artifact@v7
        with: 
          name: python-package
          path: dist/

  deploy-staging:
    name: Deploy to staging environment
    runs-on: ubuntu-latest
    needs: build
    environment: staging
      

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v8
        with:
          name: python-package
          path: dist/

      - name: Deploy to staging 
        run: |
          echo "Deploying to staging...."
          ls -la dist/

  deploy-production:
    name: Deploy to Production ENvironment
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: production

    steps:
      
      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: python-package
          path: dist/

      - name: Deploy to Production
        run: |
          echo "Deploying to production...."
          ls -la dist/













